"""Pydantic schemas for query transformation strategies (HyDE, Multi-Query, Step-Back)."""

from typing import Any, Literal

from pydantic import BaseModel, Field

from enterprise_agent.schemas.search import SearchResultItem


class HyDETransformRequest(BaseModel):
    """Payload for generating hypothetical document answer passages."""

    query: str = Field(
        ...,
        min_length=1,
        description="Original natural language query string.",
        examples=["What is the company reimbursement policy for remote ergonomic equipment?"],
    )
    num_hypotheses: int = Field(
        default=1,
        ge=1,
        le=5,
        description="Number of diverse hypothetical answer passages to generate.",
    )


class HyDETransformResponse(BaseModel):
    """Response payload containing synthetic answer documents generated by HyDE."""

    original_query: str = Field(..., description="Original input query.")
    hypothetical_documents: list[str] = Field(
        ...,
        description="Generated hypothetical answer passages.",
    )
    latency_ms: float = Field(..., description="Transformation execution duration in milliseconds.")


class MultiQueryTransformRequest(BaseModel):
    """Payload for decomposing and expanding query into multiple semantic perspectives."""

    query: str = Field(
        ...,
        min_length=1,
        description="Original search query.",
        examples=["Kafka consumer lag spike during rebalance"],
    )
    num_variations: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of alternative query perspectives to generate.",
    )


class MultiQueryTransformResponse(BaseModel):
    """Response payload containing generated query perspectives."""

    original_query: str = Field(..., description="Original input query.")
    variations: list[str] = Field(
        ...,
        description="Generated query variations and perspectives.",
    )
    latency_ms: float = Field(..., description="Transformation execution duration in milliseconds.")


class StepBackTransformRequest(BaseModel):
    """Payload for abstracting a specific query into a broader conceptual question."""

    query: str = Field(
        ...,
        min_length=1,
        description="Specific or troubleshooting query.",
        examples=["Why did MySQL return Error 1205 lock wait timeout during batch insert?"],
    )


class StepBackTransformResponse(BaseModel):
    """Response payload containing higher-level step-back concept question."""

    original_query: str = Field(..., description="Original specific input query.")
    step_back_query: str = Field(
        ...,
        description="Abstracted, high-level foundational question.",
    )
    rationale: str | None = Field(
        default=None,
        description="Optional brief explanation of why this concept grounds the query.",
    )
    latency_ms: float = Field(..., description="Transformation execution duration in milliseconds.")


class TransformedSearchRequest(BaseModel):
    """Payload for executing end-to-end retrieval with query transformation."""

    query: str = Field(
        ...,
        min_length=1,
        description="Original search query.",
    )
    strategy: Literal["hyde", "multi_query", "step_back"] = Field(
        default="multi_query",
        description="Query transformation strategy to apply prior to retrieval.",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=100,
        description="Final number of top results to return.",
    )
    candidate_k: int = Field(
        default=25,
        ge=1,
        le=200,
        description="Candidate chunks retrieved per query before deduplication or reranking.",
    )
    enable_reranking: bool = Field(
        default=True,
        description="Whether to execute Stage 2 Cross-Encoder reranking on retrieved candidates.",
    )
    filters: dict[str, Any] | None = Field(
        default=None,
        description="Optional metadata filters.",
    )
    num_variations: int = Field(
        default=3,
        ge=1,
        le=5,
        description="Number of variations for Multi-Query or hypotheses for HyDE.",
    )


class TransformedSearchResponse(BaseModel):
    """Response payload containing retrieved knowledge chunks after query transformation."""

    original_query: str = Field(..., description="Original input query.")
    strategy: str = Field(..., description="Transformation strategy applied.")
    transformed_queries: list[str] = Field(
        ...,
        description="All generated queries or hypothetical passages utilized in retrieval.",
    )
    total_results: int = Field(..., description="Count of returned chunks.")
    results: list[SearchResultItem] = Field(
        default_factory=list,
        description="Retrieved and optionally reranked chunks.",
    )
    latency_ms: float = Field(..., description="End-to-end execution duration in milliseconds.")
